name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Supabase public values (anon key is safe to expose client-side)
      EXPO_PUBLIC_SUPABASE_URL: https://hyxhlvoniyugqdogagzo.supabase.co
      EXPO_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eGhsdm9uaXl1Z3Fkb2dhZ3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3Njk1OTAsImV4cCI6MjA3NTM0NTU5MH0.VXyqCFgAoZBfQRCMy0k2ixNZVJ-GUW0tFwmePj1QntM
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/configure-pages@v5
      - name: Install deps
        run: npm ci || npm i
      - name: Build (Expo export web)
        run: npx expo export --platform web --output-dir dist
      - name: Add SPA fallback (404.html)
        run: cp dist/index.html dist/404.html
      - name: Inject runtime env (window.__ENV__)
        run: |
          cat > dist/env.js << 'EOF'
          window.__ENV__ = {
            EXPO_PUBLIC_SUPABASE_URL: '${EXPO_PUBLIC_SUPABASE_URL}',
            EXPO_PUBLIC_SUPABASE_ANON_KEY: '${EXPO_PUBLIC_SUPABASE_ANON_KEY}',
          };
          EOF
          # include env.js right after opening <head>
          sed -i '0,/<head>/s//<head>\n<script src="env.js"><\/script>/' dist/index.html dist/404.html || true
      - name: Inject debug overlay (capture runtime errors)
        run: |
          cat > dist/debug.js << 'EOF'
          (function(){
            function show(msg){
              var box=document.createElement('div');
              box.style.cssText='position:fixed;inset:8px;z-index:99999;background:rgba(0,0,0,.75);color:#fff;padding:12px;border-radius:8px;overflow:auto;font:14px system-ui,Segoe UI,Arial';
              box.innerHTML='<b>Runtime error</b><pre style="white-space:pre-wrap">'+msg+'</pre>';
              document.body.appendChild(box);
              console.error('[DEBUG OVERLAY]', msg);
            }
            window.addEventListener('error', function(e){show(String(e.error&&e.error.stack||e.message||e));});
            window.addEventListener('unhandledrejection', function(e){show(String(e.reason&&e.reason.stack||e.reason||e));});
            console.log('[DEBUG]', 'BASE', window.__BASE_PATH__, 'ENV_URL', (window.__ENV__||{}).EXPO_PUBLIC_SUPABASE_URL);
          })();
          EOF
          sed -i '0,/<head>/s//<head>\n<script src="debug.js"><\/script>/' dist/index.html dist/404.html || true
      - name: Prefix base path for GitHub Pages
        run: |
          REPO="${GITHUB_REPOSITORY#*/}"
          echo "window.__BASE_PATH__='/${REPO}';" > dist/base.js
          # Prefix absolute asset/script href/src that start with "/" to "/$REPO/"
          sed -i 's|src="/|src="/'"$REPO"'/|g' dist/index.html dist/404.html || true
          sed -i 's|href="/|href="/'"$REPO"'/|g' dist/index.html dist/404.html || true
          sed -i '0,/<head>/s//<head>\n<script src="base.js"><\/script>/' dist/index.html dist/404.html || true
          # Fix absolute paths inside bundled JS for runtime chunks (dynamic imports)
          find dist -type f -name "*.js" -print0 | xargs -0 sed -i 's|"/_expo/|"/'"$REPO"'/_expo/|g'
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
      - name: Print deployed URL
        run: |
          echo "Page URL: ${{ steps.deployment.outputs.page_url }}"
          echo "🔗 ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
